[package]
name = "rserial"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
tokio = { version = "1.38.0", features = ["full"] }
tokio-serial = "5.4.4"
