[toolchain]
channel = "stable"
components = ["rustfmt", "rustc", "rust-std", "rust-src", "cargo", "clippy"]
profile = "default"
targets = [
  "x86_64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
  "aarch64-unknown-linux-gnu",
  "aarch64-unknown-linux-musl",
  "armv7-unknown-linux-gnueabihf",
  "arm-unknown-linux-gnueabihf",
  "riscv64gc-unknown-linux-gnu",
]
